<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.example</groupId>
        <artifactId>boot-modules</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>api-doc</artifactId>
    <name>api-doc</name>
    <description>api-doc</description>
    <properties>
        <smartdoc.version>3.1.0</smartdoc.version>
    </properties>

    <dependencies>
        <!-- 引入auth 模块 -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>auth</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 引入demo-service 模块 -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>demo-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 引入 common 模块 -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- 如果有更多需要扫描的模块，请继续添加 -->
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- 父模块 pom.xml -->
            <plugin>
                <groupId>com.ly.smart-doc</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>${smartdoc.version}</version>
                <configuration>
                    <!-- 配置文件 -->
                    <configFile>${basedir}/src/main/resources/smart-doc.json</configFile>
<!--                    <projectName>boot-modules</projectName>-->
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>html</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
